// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZA0rBecn4wwcMbdCr0LuwJrBZgGal-k',
    appId: '1:355725550012:web:e5e0822a27edeecddf8bb9',
    messagingSenderId: '355725550012',
    projectId: 'blogapp-5472b',
    authDomain: 'blogapp-5472b.firebaseapp.com',
    storageBucket: 'blogapp-5472b.appspot.com',
    measurementId: 'G-PKYH73ZY34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqoLEzMw76zzK0MwDnHRMvxXIY5utDllM',
    appId: '1:355725550012:android:0063f589998ac7cddf8bb9',
    messagingSenderId: '355725550012',
    projectId: 'blogapp-5472b',
    storageBucket: 'blogapp-5472b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESy592_vBd2NntM4xwVQ6YGzqQj9gyRM',
    appId: '1:355725550012:ios:f1b0fccdd2863520df8bb9',
    messagingSenderId: '355725550012',
    projectId: 'blogapp-5472b',
    storageBucket: 'blogapp-5472b.appspot.com',
    iosClientId: '355725550012-lj5k5ujkoldlm124hbp9gds6tt5dhmot.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAESy592_vBd2NntM4xwVQ6YGzqQj9gyRM',
    appId: '1:355725550012:ios:966cee38f1eedd7bdf8bb9',
    messagingSenderId: '355725550012',
    projectId: 'blogapp-5472b',
    storageBucket: 'blogapp-5472b.appspot.com',
    iosClientId: '355725550012-ltf6lj555aqupb0ks2buqqpf814bhkfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp2.RunnerTests',
  );
}
